# Generated by Django 5.1 on 2024-10-14 15:48

import django.db.models.deletion
import transport_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=transport_app.models.get_default_role, on_delete=django.db.models.deletion.CASCADE, to='transport_app.role'),
        ),
    ]
